users/urls.py
from django.urls import path

app_name = "users"

urlpatterns = [

]

vocab/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('users/login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('users/', include('users.urls')),
    path('users/',include('django.contrib.auth.urls')),
    path('', include("words.urls")),
    path('words2/', include("words2.urls")),
    path('table/', include("table.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

words2/urls.py
from django.urls import path, include
from .views import WordListView, WordCreateView, WordUpdateView, WordDetailView, WordCardView, WordDeleteView, WordUpdateDifficultyView, MeaningCreateView, MeaningUpdateView

app_name = "words2"

urlpatterns = [
    path('', WordCardView.as_view(), name="word_cards"),
    path('list/', WordListView.as_view(), name="word_list"),
    path('create/', WordCreateView.as_view(), name="word_create"),
    path('update/<int:pk>', WordUpdateView.as_view(), name="word_update"),
    path('update_difficulty/<int:pk>', WordUpdateDifficultyView.as_view(), name="word_update_difficulty"),
    path('detail/<int:pk>', WordDetailView.as_view(), name="word_detail"),
    path('delete/<int:pk>', WordDeleteView.as_view(), name="word_delete"),

    path('meaning/create/', MeaningCreateView.as_view(), name="meaning_create"),
    path('meaning/update/<int:pk>', MeaningUpdateView.as_view(), name="meaning_create"),

]

words2/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class ModelWithTimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Word(ModelWithTimeStamp):
    word = models.CharField(max_length=100)
    difficulty = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], default=1)
    favourite = models.BooleanField(default=False, blank=True)
    translation = models.CharField(max_length=255, blank=True)
    audio_link = models.URLField(blank=True)

    class Meta:
        ordering = ('-updated_at',)

    def __str__(self):
        return self.word

    def get_absolute_url(self):
        return reverse("words2:word_detail", kwargs={"pk": self.pk})

class Meaning(ModelWithTimeStamp):
    word = models.ForeignKey(Word, on_delete=models.CASCADE, related_name="meanings")
    part_of_speech = models.CharField(max_length=50);
    definition = models.TextField(blank=True)
    synonyms = models.ManyToManyField(Word, related_name="synonyms", blank=True)
    antonyms = models.ManyToManyField(Word, related_name="antomyms", blank=True)
    example = models.TextField(blank=True)
    translation = models.CharField(max_length=255,blank=True)

    def __str__(self):
        return self.definition

    
    def get_absolute_url(self):
        return reverse("words2:word_detail", kwargs={"pk": self.word.pk})

words2/forms.py
from django import forms
from .models import Word, Meaning

from django_select2 import forms as s2forms

class SynonymsWidget(s2forms.Select2MultipleWidget):
    search_fields = [
        "word__icontains",
        # "meaning__icontains",
    ]
    model = Word
    def build_attrs(self, base_attrs, extra_attrs=None):
        attrs = super().build_attrs(base_attrs, extra_attrs=extra_attrs)
        if "class" in attrs:
            attrs["class"] += " select-dark"
        return attrs

    queryset = Word.objects.all()

class WordsWidget(s2forms.Select2Widget):
    search_fields = [
        "word__icontains",
        # "meaning__icontains",
    ]
    model = Word
    # def build_attrs(self, base_attrs, extra_attrs=None):
    #     attrs = super().build_attrs(base_attrs, extra_attrs=extra_attrs)
    #     if "class" in attrs:
    #         attrs["class"] += " select-dark"
    #     return attrs

    queryset = Word.objects.all()



class WordCreateForm(forms.ModelForm):
    style_attributes = {'style': "background: #121212; color: rgba(255,255,255,0.87); margin-bottom: 15px;"}
    word = forms.CharField(label="Word", widget=forms.TextInput(attrs=style_attributes))
    difficulty = forms.IntegerField(label="Difficulty", widget=forms.TextInput(attrs=style_attributes), required=True)

    class Meta:
        style_attributes = {'style': "background-color: black; text-color: black; margin-bottom: 30px;"}

        model = Word
        exclude = ('favourite','translation', 'audio_url')

    def save(self, commit=True):
        word = super(WordCreateForm, self).save(commit=False)
        

        if commit:
            word.save()
        return m

    def __init__(self, *args, **kwargs):
        super(WordCreateForm, self).__init__(*args, **kwargs)
        self.fields['difficulty'].initial=1

    




class MeaningCreateForm(forms.ModelForm):
    words_choices = Word.objects.all()
    style_attributes = {'style': "background: #121212; color: rgba(255,255,255,0.87); margin-bottom: 15px;"}

    # word = forms.(label="Word",max_length=100, widget=forms.TextInput(attrs=style_attributes))
    definition = forms.CharField(label="Meaning",widget=forms.Textarea(attrs=style_attributes),required=False)
    # synonyms = forms.ModelMultipleChoiceField(label="Synonyms",required=False, queryset=words_choices)
    # antonyms = forms.ModelMultipleChoiceField(label="Antonyms",required=False, queryset=words_choices)
    example = forms.CharField(label="Example", widget=forms.Textarea(attrs=style_attributes),required=False)
    translation = forms.CharField(label="Translation",max_length=250, widget=forms.TextInput(attrs=style_attributes),required=False)
    difficulty = forms.IntegerField(label="Difficulty", widget=forms.TextInput(attrs=style_attributes), required=True)

    class Meta:
        style_attributes = {'style': "background-color: black; text-color: black; margin-bottom: 30px;"}

        model = Meaning
        fields = '__all__'
        widgets = {
            "word": WordsWidget,
            "synonyms": SynonymsWidget,
            "antonyms": s2forms.Select2MultipleWidget(attrs={'class' : 'bg-dark text-white'}),
        }
class MeaningUpdateForm(MeaningCreateForm):
    word = forms.ModelChoiceField(label="Word",widget=WordsWidget,disabled=False, queryset=Word.objects.all())

words2/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import redirect, get_object_or_404

from .models import Word, Meaning
from .forms import WordCreateForm, MeaningCreateForm, MeaningUpdateForm
# Create your views here.

class WordListView(generic.ListView):
    model = Word
    context_object_name = "word_list"
    template_name = "words2/word_list.html"

class WordCardView(generic.ListView):
    model = Word
    context_object_name = "word_list"
    template_name = "words2/word_cards.html"


class WordCreateView(generic.CreateView):
    model = Word
    form_class = WordCreateForm
    template_name = "words2/word_create.html"
    success_url = reverse_lazy('words2:word_cards')

    def get_context_data(self):
        context = super(WordCreateView, self).get_context_data()
        context['action'] = "Add"
        return context

class MeaningCreateView(generic.CreateView):
    model = Meaning
    form_class = MeaningCreateForm
    template_name = "words2/meaning_create.html"
    success_url = reverse_lazy('words2:word_cards')

    def get_context_data(self):
        context = super(MeaningCreateView, self).get_context_data()
        context['action'] = "Add"
        return context

class MeaningUpdateView(generic.UpdateView):
    model = Meaning
    form_class = MeaningUpdateForm
    template_name = "words2/meaning_create.html"
    success_url = reverse_lazy('words2:word_cards')

    def get_context_data(self):
        context = super(MeaningUpdateView, self).get_context_data()
        context['action'] = "Update"
        return context

class WordUpdateView(generic.UpdateView):
    model = Word
    form_class = WordCreateForm
    template_name = "words2/word_create.html"
    success_url = reverse_lazy('words2:word_cards')

    def get_context_data(self,**kwargs):
        context = super(WordUpdateView, self).get_context_data()
        context['action'] = "Update"
        return context

class WordUpdateDifficultyView(generic.View):
    def post(self, request, pk):
        word = get_object_or_404(Word,id=pk)
        word.difficulty = request.POST.get('difficulty')
        word.save();
        return redirect(reverse_lazy('words2:word_cards'))

class WordDetailView(generic.DetailView):
    model = Word
    template_name = "words2/word_detail.html"
    context_object_name = "word"

class WordDeleteView(generic.DeleteView):
    model = Word
    success_url = reverse_lazy("words2:word_cards")


# def list(request):
#     return render(request, "words/list.html", context={})

words2/templates/words2/meaning_create.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 

{% block title %} New Word {% endblock title %} 

{% block style %} 
    {{ form.media.css }}

    <style>
    span.select2-selection.select2-selection--multiple{
        background: #121212;
        color: white;
    }

    span.select2-results{
        background: #121212;
        color: white;

    }

    .select2-container--default .select2-selection--multiple .select2-selection__choice{
        background-color: #121212;
    }

    input.select2-search__field{
        color: rgba(255,255,255,0.87);
        border-color: rgba(255,255,255,0.87);
        background: #121212;
    }

    .select2-container--default .select2-results__option[aria-selected=true] {
    background-color: #333333;
}

    span.select2-selection__rendered{
        background: #121212;
       color: rgba(255,255,255,0.87);

    }

    #select2-id_word-container{
       color: rgba(255,255,255,0.87);

    }

    span.select2-search.select2-search--dropdown{
        background: #121212;

    }
    </style> 
{% endblock style %} 

{% block content %}
    <h2 style="margin: 3vh 0">Add a New Meaning</h2>
    <form action="" method="post">
    {% csrf_token %} 
    {{ form|crispy}}
    <button class="btn btn-success" type="submit">{{ action }}</button>
    </form>

{% endblock content %} 

{% block script %} 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    {{ form.media.js }} 
{% endblock script %}

words2/templates/words2/word_cards.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}Cards{% endblock title %}

{% block content %}
    <div class="row">
        {% for word in word_list %}
            <div class="col-12 col-md-6 col-lg-4 mb-2">
                <div class="card mx-auto bg-dark ">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-6 text-left">
                                <h1>{{ word.word }}</h1>
                            </div>
                            <div class="col-6 mb-1 pt-2 text-end">

                                <form action="{% url 'words:word_delete' word.id %}" class="form-inline" method="POST">
                                {% csrf_token %}
                                    <a href={% url "words:word_update" word.id %} class="btn btn-outline-info mr-auto"><i class="fa fa-edit" aria-hidden="true"></i></a>
                                    <button class="btn btn-outline-danger mr-auto"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                </form> 
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                        <div class="col-sm-6">
                            <div class="card-body">
                            {% for meaning in word.meanings.all  %}
                                <h5 class="card-title">{{ meaning.definition }}</h5>
                            {% endfor %}
                            <p class="card-text"><i>{{ word.example }}</i></p>
                            <p class="card-text">{{ word.translation }}</p>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="row">
                            <div class="col-sm-12">
                                <div class="card text-success bg-dark border-success mb-3">
                                <div class="card-header">Synonyms</div>
                                <div class="card-body text-success">
                                    <h5 class="card-title">
                                    {% for synonym in word.synonyms.all  %}
                                            <a class="text-success text-underlined" href={% url "words:word_detail" synonym.id %} style="text-decoration: none;"><u>{{ synonym.word }}</u></a> {% if not forloop.last %}| {% endif %} 
                                        {% endfor %}
                                    </h5>
                                </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="card text-danger bg-dark border-danger mb-3">
                                <div class="card-header">Antonyms</div>
                                <div class="card-body text-danger">
                                    <h5 class="card-title">
                                        {% for antonym in word.antonyms.all  %}
                                            <a class="text-danger" href={% url "words:word_detail" antonym.id %} style="text-decoration: none;">{{ antonym.word }}</a> {% if not forloop.last %}| {% endif %} 
                                        {% endfor %}
                                    </h5>
                                </div>
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-12 text-danger">
                            <div class="row">
                                {% for _ in '0123456789'|make_list %}
                                <div class="col-1">
                                    <form class="form-inline" action={% url 'words:word_update_difficulty' word.pk %} method="POST">
                                    {% csrf_token %}
                                        <input type="hidden" name="difficulty" value="{{ forloop.counter }}">
                                    {% if forloop.counter <= word.difficulty %}
                                            <button type="submit" class="btn btn-outline-danger" style="border: none;"><i class="fa fa-circle" aria-hidden="true"></i></button>
                                    {% else %}
                                        <button type="submit" class="btn btn-outline-danger" style="border: none;"><i class="fa fa-circle-thin" aria-hidden="true"></i></button>
                                    {% endif %}
                                    </form>
                                </div>
                                {% endfor %}
                            </div>
                            </div>
                            <div class="col-12">
                                <p class="text-end text-muted"> updated {{ word.updated_at|naturaltime }} </p>
                            </div>
                        </div>
                       
                    </div>
                    </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

words2/templates/words2/word_create.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 

{% block title %} New Word {% endblock title %} 

{% block style %} 
    {{ form.media.css }}

    <style>
    span.select2-selection.select2-selection--multiple{
        background: #121212;
        color: white;
    }

    span.select2-results{
        background: #121212;
        color: white;

    }

    .select2-container--default .select2-selection--multiple .select2-selection__choice{
        background-color: #121212;
    }

    input.select2-search__field{
        color: rgba(255,255,255,0.87);
        border-color: rgba(255,255,255,0.87);
    }

    .select2-container--default .select2-results__option[aria-selected=true] {
    background-color: #333333;
}
    </style> 
{% endblock style %} 

{% block content %}
    <h2 style="margin: 3vh 0">Add a New Word</h2>
    <form action="" method="post">
    {% csrf_token %} 
    {{ form|crispy}}
    <button class="btn btn-success" type="submit">{{ action }}</button>
    </form>

{% endblock content %} 

{% block script %} 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    {{ form.media.js }} 
{% endblock script %}

words2/templates/words2/word_detail.html
{% extends 'base.html' %} {% comment %} {% extends 'base.html' %} {% block
content %}
<div class="card text-white bg-dark mb-3">
  <div class="card-header">
    <h1>{{ word.word }}</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ word.meaning }}</h5>
    <p class="card-text">{{ word.example}}</p>
    <div class="row">
      <div class="col-sm-6">
        <div class="card text-success bg-dark border-success mb-3">
          <div class="card-header">Synonyms</div>
          <div class="card-body text-success">
            <h5 class="card-title">Success card title</h5>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card text-danger bg-dark border-danger mb-3">
          <div class="card-header">Antonyms</div>
          <div class="card-body text-danger">
            <h5 class="card-title">Danger card title</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %} {% endcomment %} 
{% block content %}
<div class="card bg-dark mb-3">
  <div class="card-header">
    <h1>{{ word.word }}</h1>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-8">
        <div class="card-body">
          <h5 class="card-title">{{ word.meaning }}</h5>
          <p class="card-text"><i>{{ word.example}}</i></p>
          <p class="card-text">{{ word.translation}}</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="row">
          <div class="col-sm-12">
            <div class="card text-success bg-dark border-success mb-3">
              <div class="card-header">Synonyms</div>
              <div class="card-body text-success">
                <h5 class="card-title">
                {% for synonym in word.synonyms.all  %}
                        <a class="text-success text-underlined" href={% url "words:word_detail" synonym.id %} style="text-decoration: none;"><u>{{ synonym.word }}</u></a> {% if not forloop.last %}| {% endif %} 
                    {% endfor %}
                </h5>
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="card text-warning bg-dark border-warning mb-3">
              <div class="card-header">Antonyms</div>
              <div class="card-body text-warning">
                <h5 class="card-title">
                    {% for antonym in word.antonyms.all  %}
                        <a class="text-warning" href={% url "words:word_detail" antonym.id %} style="text-decoration: none;">{{ antonym.word }}</a> {% if not forloop.last %}| {% endif %} 
                    {% endfor %}
                </h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
        <div class="col-sm-6 mb-1">
            <a href={% url "words:word_update" word.id %}><button class="btn btn-outline-info col-12" > Edit</button></a>
        </div>
        <div class="col-sm-6 ">
            <a href={% url "words:word_update" word.id %}><button class="btn btn-outline-danger col-12"> Delete</button> </a>
        </div>
    </div>
  </div>
  </div>
  {% endblock content %}

words2/templates/words2/word_list.html
{% extends "base.html" %} 
{% load tz %}
{% load humanize %}
{% block content %}
<h1>hello</h1>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Word</th>
      <th>Meaning</th>
      <th>Synonyms</th>
      <th>Antonyms</th>
      <th>Example</th>
      <th>Translation</th>
      <th>Created At</th>
    </tr>
  </thead>
  {% for word in word_list %}
  <tr>
    <td>{{ word.word }}</td>
    <td>{{ word.meaning }}</td>
    <td>
      {% for synonym in word.synonyms.all %} {{synonym.word }} {% endfor %}
    </td>
    <td>
      {% for antonym in word.antonyms.all %} {{antonym.word }} {% endfor %}
    </td>
    <td>{{ word.example }}</td>
    <td>{{ word.translation }}</td>
    <td> {{ word.created_at|naturaltime }}</td>
   {% comment %} <td> {% timezone "Asia/Kathmandu" %}  {{ word.created_at }} {% endtimezone %} </td> {% endcomment %}
  </tr>
  {% endfor %}
</table>
{% endblock content %}