users/urls.py
from django.urls import path

app_name = "users"

urlpatterns = [

]

vocab/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('users/login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('users/', include('users.urls')),
    path('users/',include('django.contrib.auth.urls')),
    path('', include("words.urls")),
    path('words2/', include("words2.urls")),
    path('table/', include("table.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

words/urls.py
from django.urls import path, include
from .views import WordListView, WordCreateView, WordUpdateView, WordDetailView, WordCardView, WordDeleteView, WordPartialUpdateView, WordTableView

app_name = "words"

urlpatterns = [
    path('', WordCardView.as_view(), name="word_cards"),
    path('list/', WordListView.as_view(), name="word_list"),
    path('table/', WordTableView.as_view(), name="word_table"),
    path('create/', WordCreateView.as_view(), name="word_create"),
    path('update/<int:pk>', WordUpdateView.as_view(), name="word_update"),
    path('partial_update/<int:pk>', WordPartialUpdateView.as_view(), name="word_partial_update"),
    path('detail/<int:pk>', WordDetailView.as_view(), name="word_detail"),
    path('delete/<int:pk>', WordDeleteView.as_view(), name="word_delete"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Home{% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'fa/css/font-awesome.min.css' %}">
    {% block style %}{% endblock style %}
  </head>
  <body style="background: #121212; color: rgba(255,255,255,0.87)">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href={% url "words:word_cards" %}>Vocab</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              {% comment %} <a class="nav-link active" aria-current="page" href="#">Home</a> {% endcomment %}
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url "words:word_create" %}>Add Word</a>
            </li>
            {% comment %} <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li> {% endcomment %}
            {% comment %} <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li> {% endcomment %}
          </ul>
          <form action={% url "words:word_cards" %} method="GET" class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              name="search_term"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container" style="margin-top: 70px;">{% block content %} {% endblock content %}</div>

    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"
    ></script>
    {% block script %}{% endblock script %}
  </body>
</html>